drop table user if exists;
create table user (
    id bigint generated by default as identity
  , username varchar(255)
  ,password varchar(50)
  , age int
  , birthday TIMESTAMP
  , primary key (id)
);